In [2]:
import torch

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [4]:
shape = (2,3,)

ones_tensor =  torch.ones(shape)
print(ones_tensor)

zeros_tensor = torch.zeros(shape)

torch.manual_seed(1789)

rand_tensor = torch.rand(shape) 
print(rand_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9631, 0.4014, 0.7564],
        [0.5782, 0.5438, 0.1929]])


In [5]:
empty_tensor = torch.empty(shape)

print(empty_tensor)

tensor([[8.7861e-43, 1.6753e+35, 2.7891e+29],
        [2.5417e+08, 2.2648e+20, 1.5745e+25]])


In [6]:
x= torch.empty(2,2,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [7]:
tensor  = torch.rand(3,2)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [8]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print("Helo")

Helo


In [9]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5
print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [11]:
powers2 = [twos ** torch.tensor([[1, 2], [3, 4]])]
print(powers2)

[tensor([[ 2.,  4.],
        [ 8., 16.]])]


In [12]:
rand = torch.rand(2,4)
doubled = rand * (torch.ones(1,4)*2)
print(rand)
print(doubled)

tensor([[0.2569, 0.8153, 0.3774, 0.6209],
        [0.8973, 0.6783, 0.8594, 0.6721]])
tensor([[0.5138, 1.6306, 0.7549, 1.2419],
        [1.7946, 1.3567, 1.7187, 1.3442]])


In [13]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(3,2)
print(b)

tensor([[[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]]])


In [14]:
c = a * torch.rand(3,1)
print(c)

tensor([[[0.4606, 0.4606],
         [0.7056, 0.7056],
         [0.5921, 0.5921]],

        [[0.4606, 0.4606],
         [0.7056, 0.7056],
         [0.5921, 0.5921]],

        [[0.4606, 0.4606],
         [0.7056, 0.7056],
         [0.5921, 0.5921]],

        [[0.4606, 0.4606],
         [0.7056, 0.7056],
         [0.5921, 0.5921]]])


In [16]:
i3= torch.tensor([[3.0,0.0],[0.0,3.0]])

print(torch.svd(i3))

torch.return_types.svd(
U=tensor([[1., 0.],
        [0., 1.]]),
S=tensor([3., 3.]),
V=tensor([[1., 0.],
        [0., 1.]]))


In [40]:
a=torch.rand(26,26)
print(a)
c=a.unsqueeze(0)
print(c)

tensor([[0.3954, 0.7260, 0.2009, 0.9918, 0.6216, 0.8688, 0.3366, 0.8752, 0.3480,
         0.9764, 0.6829, 0.3566, 0.2061, 0.0160, 0.0924, 0.3136, 0.3663, 0.7628,
         0.4904, 0.9694, 0.5030, 0.2474, 0.1266, 0.1417, 0.5149, 0.6553],
        [0.0717, 0.5030, 0.8813, 0.4959, 0.4578, 0.3884, 0.2327, 0.2408, 0.7233,
         0.7631, 0.9567, 0.7466, 0.0830, 0.5621, 0.1219, 0.7852, 0.2502, 0.0147,
         0.5121, 0.8251, 0.2971, 0.6637, 0.6100, 0.3919, 0.2673, 0.6582],
        [0.8297, 0.3535, 0.5507, 0.7158, 0.4354, 0.2287, 0.8364, 0.9855, 0.1275,
         0.1657, 0.1681, 0.0664, 0.4843, 0.6106, 0.3143, 0.7373, 0.7189, 0.7830,
         0.4500, 0.2482, 0.0092, 0.8093, 0.0547, 0.8578, 0.1315, 0.7686],
        [0.9386, 0.7261, 0.6105, 0.2236, 0.0880, 0.2916, 0.1772, 0.8724, 0.4654,
         0.6352, 0.3848, 0.1266, 0.6828, 0.9633, 0.2467, 0.8665, 0.5405, 0.2753,
         0.1459, 0.6278, 0.3416, 0.6812, 0.2877, 0.4996, 0.8694, 0.7304],
        [0.9471, 0.7558, 0.4037, 0.1169, 0.0096, 0.5987,